[theme]
# Color principal para elementos interactivos (botones, sliders, etc.)
primaryColor="#FFFF00"

# Color de fondo principal de la aplicaci√≥n
backgroundColor="#000000"

# Color de fondo para formularios, cajas de texto y otros elementos
secondaryBackgroundColor="#31333F"

# Color del texto principal
textColor="#FFFF00"

# Tipo de fuente a utilizar en toda la app
font="sans serif"
